# Generated by Django 3.2.2 on 2021-05-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profileImage',
            new_name='profile_image_url',
        ),
    ]
