# Generated by Django 3.2.2 on 2021-05-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='eventcategory',
            name='unique_event_category',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcategory'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventCategoryType',
        ),
    ]
