# Generated by Django 3.2.2 on 2021-05-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0002_auto_20210511_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedEvent',
            new_name='EventLike',
        ),
        migrations.RemoveConstraint(
            model_name='eventlike',
            name='unique_user_liked_event',
        ),
        migrations.RenameField(
            model_name='eventcomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.AddConstraint(
            model_name='eventlike',
            constraint=models.UniqueConstraint(fields=('user_id', 'event_id'), name='unique_user_event_like'),
        ),
    ]
