# Generated by Django 3.2.2 on 2021-05-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210511_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlike',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventsignup',
            options={'ordering': ['-created_at']},
        ),
    ]
